### PR TITLE
Css fix

### PR DESCRIPTION
**Pull request by tawfiknasser**
issue #86 
- added search icon 
- head bar stick to the top 
- added border-radius to components

### CODE REVIEW

**Comment by shiryz** [comment]
Burger menu margin:
screenshot from 2018-09-19 18-18-42

**Comment by shiryz** [comment]
Needs padding:
screenshot from 2018-09-19 18-27-43

**Comment by shiryz** [comment]
@MynahMarie, it's working for me :+1:

**Comment by tawfiknasser** [comment]
@MynahMarie do you have the DB url in your config ?
If it's still breaking can you attach please screenshot for the error ?

**Comment by tawfiknasser** [comment]
> Needs padding:
> screenshot from 2018-09-19 18-27-43

**Pull request merged**
